### PR TITLE
Fix Text Drap Problem

### PR DESCRIPTION
**Pull request by Littlegolden**
A method from flarum.aTowerLight.cn.

### CODE REVIEW

**Comment by Littlegolden** [comment]
js files still need to be compiled after merge this pull request.

**Comment by clarkwinkelmann** [comment]
What exactly does this solve ?

Also you have some `console.log` calls leftover.

**Comment by Littlegolden** [comment]
After installing fof / upload, you will not be able to drag and drop text. This method can repair the function of dragging and dropping text, and does not affect the drag and drop file to upload.

【Video】
https://drive.google.com/open?id=1Ob7A6d6FIqqTdqFK3BwW65BoBpLmdMfq

**Comment by clarkwinkelmann** [comment]
I made a more advanced fix that covers more cases in https://github.com/FriendsOfFlarum/upload/commit/d72f3b7a66f81e9123f077d44c76a4f68fa94eba which has been released with the new 0.8.5 version.

Thanks for your help!

**Pull request closed without merging**
