### PR TITLE
Extract error message strings to be translatable

### PR DESCRIPTION
**Pull request by julakali**
I extracted three error message strings because i needed them to be translatable via Linguist. I guess this makes sense for everyone.

### CODE REVIEW

**Comment by lfpoulain** [comment]
Exactly what I was looking for :)

**Comment by clarkwinkelmann** [comment]
Or maybe even `upload_errors` in the namespace, so we have some context as to what the errors refer to.

And `validation_error` could be `invalid_file` or `could_not_detect_mime` for example to better reflect what it is.

**Comment by kalinjul** [comment]
I changed the namespaces as suggested and removed the trans() method, which was initially copied from AbstractTemplate.php, i thought you may want it that way (if there's something very different in this case, you may explain or just ignore as I don't really know PHP).
Also added the trailing newline and removed $msg variable.

**Comment by clarkwinkelmann** [comment]
I had not noticed that two translations shared the same value... But I guess in this context it's easier for us to reuse translations than doing the effort to make two different keys. Those errors should rarely appear and won't be super helpful in troubleshooting anyway.

**Pull request merged**
