### PR TITLE
Fix Condition when Text Preview should be shown

### PR DESCRIPTION
**Pull request by edgeinfinity1**
**Fixes #0000**

**Changes proposed in this pull request:**
Fixes the "expand" button's misbehavior while using Text Preview.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related [Flarum core extension PR's](https://github.com/flarum/core/pulls): (Omit this section if irrelevant)

### CODE REVIEW

**Comment by DavideIadeluca** [comment]
Hi @edgeinfinity1 thanks for your contribution! Please provide steps to reproduce the issue, and maybe add some screenshots/screencasts before and after the change. Thanks!

**Comment by edgeinfinity1** [comment]
> Hi @edgeinfinity1 thanks for your contribution! Please provide steps to reproduce the issue, and maybe add some screenshots/screencasts before and after the change. Thanks!

I'm sorry for not being able to provide screenshots before the change, because my forum is already in production state.
It's very easy to reproduce the problem: 

1. use "Text Preview" for mime text files.
2. upload a file within 5 lines, and the expand button **shows and does nothing**.
3. upload a file more than 5 lines, and there is **no expand button at all**.

this problem is obviously because of a misjudgement in rather the file should be expandable, or say just reversed.

**Review by DavideIadeluca — COMMENTED** [review]
Sorry for the delay, I actually looked into this month's back but didn't get around replying..

The change introduced here does improve the behaviour, but there is still an edge case left when the text file has 5 lines of text and an empty last line, if I recall correctly. I'll try to have another go..

**Comment by DavideIadeluca** [comment]
Made some changes, seems to be working now as expected

Screenshot 2024-11-04 at 07 41 10

Screenshot 2024-11-04 at 07 41 23

**Review by DavideIadeluca — APPROVED** [review]

**Review by imorland — APPROVED** [review]

**Pull request merged**
